# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sunweather"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tobi Frank"]
  s.date = "2013-10-18"
  s.description = "Provides sunrise/sunset and weather info for given address."
  s.email = "tobifrank38@gmail.com"
  s.executables = ["sunweather"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/sunweather",
    "lib/geo.rb",
    "lib/runner.rb",
    "lib/sun.rb",
    "lib/weather.rb",
    "spec/geo_spec.rb",
    "spec/spec_helper.rb",
    "spec/sun_spec.rb",
    "spec/weather_spec.rb",
    "sunweather.gemspec",
    "temp"
  ]
  s.homepage = "http://github.com/tobifrank/sunweather"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Provides sunrise/sunset and weather info for given address."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<geocoder>, ["~> 1.1.8"])
      s.add_development_dependency(%q<json>, ["~> 1.8.0"])
      s.add_development_dependency(%q<capybara>, ["~> 2.1.0"])
      s.add_development_dependency(%q<xml-simple>, ["~> 1.1.2"])
      s.add_development_dependency(%q<awesome_print>, ["~> 1.1.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<geocoder>, ["~> 1.1.8"])
      s.add_dependency(%q<json>, ["~> 1.8.0"])
      s.add_dependency(%q<capybara>, ["~> 2.1.0"])
      s.add_dependency(%q<xml-simple>, ["~> 1.1.2"])
      s.add_dependency(%q<awesome_print>, ["~> 1.1.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<geocoder>, ["~> 1.1.8"])
    s.add_dependency(%q<json>, ["~> 1.8.0"])
    s.add_dependency(%q<capybara>, ["~> 2.1.0"])
    s.add_dependency(%q<xml-simple>, ["~> 1.1.2"])
    s.add_dependency(%q<awesome_print>, ["~> 1.1.0"])
  end
end

